<?php
/**
 * TÝMY LIONS
 *
 * Každý tým = jedna stránka (URL = klíč pole, stejné jako na původním webu).
 *
 *  csh        – soutěže na handball.cz, ze kterých se AUTOMATICKY tahají rozpisy, výsledky a tabulky.
 *               'slug' je poslední část adresy soutěže, např. handball.cz/souteze/zeny/liga-zeny-cechyyy
 *               'sex' je 'zeny' nebo 'muzi' (podle adresy). Na novou sezónu stačí přepsat slug.
 *  sportlyzer – ID skupiny ve Sportlyzeru (TÝM widget + KALENDÁŘ widget).
 *  in_menu    – zobrazit v menu LIONS TÝMY (pořadí = pořadí v tomto souboru)
 *  partners   – partneři týmu: [web, logo, název] – sekce PARTNEŘI TÝMU se ukáže jen když tu někdo je
 *  widgets    – libovolné další widgety (Sportlyzer apod.). Buď 'iframe' => URL, nebo 'html' => vložený kód.
 */
return [

    'pripravka' => [
        'in_menu'  => true,
        'menu_label' => 'PŘÍPRAVKA Hostivice',
        'title'    => 'PŘÍPRAVKA Hostivice',
        'label'    => 'LIONS PŘÍPRAVKA',
        'home_tag' => 'PŘÍPRAVKA',
        'photo'    => '2024/06/NK3_8732-topaz-denoise-exposure-faceai-sharpen-color-02.png',
        'heading'  => 'PŘÍPRAVKA Hostivice',
        'info'     => ['děvčata a chlapci ročníku 2018 a mladší (sezóna 26/27), **trenér:** Daniel K. mladší'],
        'training_title' => 'TRÉNINK 2x týdně:',
        'training' => [
            'ÚTERÝ … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
            'ČTVRTEK … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['půldenní turnaje cca 1 měsíčně o víkendu', 'členský příspěvek pololetí: 3.900,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92460,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_MINIZACTVO.png',
        'csh'      => [],
    ],

    'pripravka-chyne' => [
        'in_menu'  => false,
        'menu_label' => 'PŘÍPRAVKA Chýně',
        'title'    => 'PŘÍPRAVKA Chýně',
        'label'    => 'LIONS PŘÍPRAVKA',
        'home_tag' => 'PŘÍPRAVKA',
        'photo'    => '2024/06/NK3_8732-topaz-denoise-exposure-faceai-sharpen-color-02.png',
        'heading'  => 'PŘÍPRAVKA CHÝNĚ',
        'info'     => ['děvčata a chlapci ročníku 2018 a mladší (sezóna 26/27), **trenér:** Daniel K. mladší'],
        'training_title' => 'TRÉNINK 2x týdně:',
        'training' => [
            'PONDĚLÍ … 16:00h – 17:30h … ZŠ VIDA Chýně',
            'STŘEDA … 16:00h – 17:30h … ZŠ VIDA Chýně',
        ],
        'notes'    => ['půldenní turnaje cca 1 měsíčně o víkendu', 'členský příspěvek pololetí: 3.900,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92460,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_MINIZACTVO.png',
        'csh'      => [],
    ],

    'minizactvo' => [
        'in_menu'  => true,
        'menu_label' => 'MINIžactvo Hostivice',
        'title'    => 'MINIžactvo Hostivice',
        'label'    => 'LIONS MINIŽACTVO',
        'home_tag' => 'MINIŽACTVO',
        'photo'    => '2024/06/NK3_8704-topaz-denoise-exposure-faceai-sharpen-color-02-1.png',
        'heading'  => 'MINIŽACTVO Hostivice',
        'info'     => ['děvčata a chlapci ročníku 2016 a 2017 (sezóna 26/27), **trenér:** Daniel K. starší'],
        'training_title' => 'TRÉNINK 2x týdně:',
        'training' => [
            'ÚTERÝ … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
            'ČTVRTEK … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['půldenní turnaje cca 1 měsíčně o víkendu', 'členský příspěvek pololetí: 3.900,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92455,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_MINIZACTVO.png',
        'csh'      => [],
    ],

    'minizactvo-chyne' => [
        'in_menu'  => false,
        'menu_label' => 'MINIžactvo Chýně',
        'title'    => 'MINIžactvo Chýně',
        'label'    => 'LIONS MINIŽACTVO',
        'home_tag' => 'MINIŽACTVO',
        'photo'    => '2024/06/NK3_8704-topaz-denoise-exposure-faceai-sharpen-color-02-1.png',
        'heading'  => 'MINIŽACTVO Chýně',
        'info'     => ['děvčata a chlapci ročníku 2016 a 2017 (sezóna 26/27), **trenér:** Daniel K. starší'],
        'training_title' => 'TRÉNINK 2x týdně:',
        'training' => [
            'PONDĚLÍ … 16:00h – 17:30h … ZŠ VIDA Chýně',
            'STŘEDA … 16:00h – 17:30h … ZŠ VIDA Chýně',
        ],
        'notes'    => ['půldenní turnaje cca 1 měsíčně o víkendu', 'členský příspěvek pololetí: 3.900,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92455,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_MINIZACTVO.png',
        'csh'      => [],
    ],

    'zakyne-mladsi' => [
        'in_menu'  => true,
        'menu_label' => 'ŽÁKYNĚ mladší',
        'title'    => 'Žákyně mladší',
        'label'    => 'LIONS ŽÁKYNĚ MLADŠÍ',
        'home_tag' => 'ŽÁKYNĚ MLADŠÍ',
        'photo'    => '2024/06/NK3_8903_02.png',
        'heading'  => 'ŽÁKYNĚ MLADŠÍ',
        'info'     => ['děvčata ročníku 2014 a 2015 (sezóna 26/27), **trenér:** Daniel K. starší'],
        'training_title' => 'TRÉNINK 4x týdně:',
        'training' => [
            'PONDĚLÍ … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
            'ÚTERÝ … 18:00h – 19:30h … HALA ZŠ VIDA Chýně',
            'STŘEDA … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
            'ČTVRTEK … 18:00h – 19:30h … HALA ZŠ VIDA Chýně',
        ],
        'notes'    => ['jednodenní turnaj o víkendu cca co 2 týdny + nepravidelné vícedenní turnaje', 'členský příspěvek pololetí: 4.400,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92462,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_ZACKY.png',
        'csh'      => [
            ['slug' => 'stredoceska-liga-mladsich-zakyn',                    'sex' => 'zeny'],
            ['slug' => 'stredoceska-kvalifikace-o-desetiboj-mladsi-zakyne', 'sex' => 'zeny'],
        ],
    ],

    'zaci-mladsi' => [
        'in_menu'  => true,
        'menu_label' => 'ŽÁCI mladší',
        'title'    => 'Žáci mladší',
        'label'    => 'LIONS ŽÁCI MLADŠÍ',
        'home_tag' => 'ŽÁCI MLADŠÍ',
        'photo'    => '2024/06/NK3_8830_02.png',
        'heading'  => 'ŽÁCI MLADŠÍ',
        'info'     => ['chlapci ročníku 2014 a 2015 (sezóna 26/27), **trenér:** PANENKA Lenka a PANENKA Jiří'],
        'training_title' => 'TRÉNINK 3x týdně:',
        'training' => [
            'PONDĚLÍ … 17:15h – 18:45 … LIONS Aréna Hostivice – Břve',
            'STŘEDA … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
            'PÁTEK … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['jednodenní turnaj o víkendu cca co 2 týdny + nepravidelné vícedenní turnaje', 'členský příspěvek pololetí: 4.400,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92456,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_ZACI.png',
        'csh'      => [
            ['slug' => 'stredoceska-liga-mladsich-zaku-chlapci',          'sex' => 'muzi'],
            ['slug' => 'stredoceska-kvalifikace-o-desetiboj-mladsi-zaci', 'sex' => 'muzi'],
        ],
    ],

    'zakyne-starsi' => [
        'in_menu'  => true,
        'menu_label' => 'ŽÁKYNĚ starší',
        'title'    => 'Žákyně starší',
        'label'    => 'LIONS ŽÁKYNĚ STARŠÍ',
        'home_tag' => 'ŽÁKYNĚ STARŠÍ',
        'photo'    => '2024/06/NK3_8908_02.png',
        'heading'  => 'ŽÁKYNĚ STARŠÍ',
        'info'     => ['děvčata ročníku 2012 a 2013 (sezóna 26/27), **trenér:** Kachman Tomáš, Barátová Jana'],
        'training_title' => 'TRÉNINK 4x týdně:',
        'training' => [
            'PONDĚLÍ … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
            'ÚTERÝ … 18:00h – 19:30h … HALA ZŠ VIDA Chýně',
            'STŘEDA … 16:00h – 17:30h … LIONS Aréna Hostivice – Břve',
            'PÁTEK … 18:00h – 19:30h … HALA ZŠ VIDA Chýně',
        ],
        'notes'    => ['jednodenní turnaj o víkendu cca co 2 týdny + nepravidelné vícedenní turnaje', 'členský příspěvek pololetí: 4.900,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92463,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_ZACKY.png',
        'csh'      => [
            ['slug' => 'stredoceska-liga-starsich-zakyn', 'sex' => 'zeny'],
            ['slug' => 'zl-zakyne-hl-cast-26',            'sex' => 'zeny'],
            ['slug' => 'str-kval-zl-divky',               'sex' => 'zeny'],
        ],
    ],

    'zaci-starsi' => [
        'in_menu'  => true,
        'menu_label' => 'ŽÁCI starší',
        'title'    => 'Žáci starší',
        'label'    => 'LIONS ŽÁCI STARŠÍ',
        'home_tag' => 'ŽÁCI STARŠÍ',
        'photo'    => '2024/06/NK3_8960-topaz-denoise-faceai-sharpen-02.png',
        'heading'  => 'ŽÁCI STARŠÍ',
        'info'     => ['chlapci ročníku 2012 a 2013 (sezóna 26/27), **trenér:** Kürti Oliver'],
        'training_title' => 'TRÉNINK 4x týdně:',
        'training' => [
            'PONDĚLÍ … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
            'ÚTERÝ … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
            'STŘEDA … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
            'ČTVRTEK … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['jednodenní turnaj o víkendu cca co 2 týdny + nepravidelné vícedenní turnaje', 'členský příspěvek pololetí: 4.900,- Kč'],
        'cta'      => true,
        'register' => true,
        'sportlyzer' => 92457,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_ZACI.png',
        'csh'      => [
            ['slug' => 'prvni-stredoceska-liga-starsiho-zactva', 'sex' => 'muzi'],
            ['slug' => 'zl-zaci-hl-cast-26',                     'sex' => 'muzi'],
            ['slug' => 'stredoceska-kvalifikace-zakovska-liga-chlapcu', 'sex' => 'muzi'],
        ],
    ],

    'dorostenky-mladsi' => [
        'in_menu'  => true,
        'menu_label' => 'DOROSTENKY mladší',
        'title'    => 'Dorostenky mladší',
        'label'    => 'LIONS DOROSTENKY MLADŠÍ',
        'home_tag' => 'DOROSTENKY MLADŠÍ',
        'photo'    => '2025/12/P1011385-topaz-rawdenoise-sharpen-color-face.png',
        'heading'  => 'DOROSTENKY MLADŠÍ',
        'info'     => ['děvčata ročníku 2010 a 2011 (sezóna 26/27), **trenérka:** ADAMOVÁ Kateřina'],
        'training_title' => 'TRÉNINK 4x týdně:',
        'training' => [
            'PONDĚLÍ … 18:00h – 19:00h … LIONS FitZona Hostivice – Břve',
            'ÚTERÝ … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
            'STŘEDA … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'PÁTEK … 17:15h – 18:45h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['utkání 2. ligy házené dorostenek mladších o víkendu', 'členský příspěvek pololetí: 5.900,- Kč'],
        'cta'      => false,
        'register' => false,
        'sportlyzer' => 92464,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_DOROSTENCI.png',
        'csh'      => [
            ['slug' => '2-liga-mladsi-dorostenky-cechy', 'sex' => 'zeny'],
        ],
    ],

    'dorost-mladsi' => [
        'in_menu'  => true,
        'menu_label' => 'DOROSTENCI mladší',
        'title'    => 'Dorost mladší',
        'label'    => 'LIONS DOROST MLADŠÍ',
        'home_tag' => 'DOROSTENCI MLADŠÍ',
        'photo'    => '2024/06/NK3_9140-topaz-faceai-sharpen_02.png',
        'heading'  => 'DOROSTENCI MLADŠÍ',
        'info'     => ['chlapci ročníku 2010 a 2011 (sezóna 26/27)', '**trenér:** RAMS Petr, ČEPÁK Radoslav, KRAUS Karel'],
        'training_title' => 'TRÉNINK 4x týdně:',
        'training' => [
            'PONDĚLÍ … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'ÚTERÝ … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'ČTVRTEK … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'PÁTEK … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['utkání 2. ligy házené dorostu mladšího o víkendu', 'členský příspěvek pololetí: 5.900,- Kč'],
        'cta'      => false,
        'register' => false,
        'sportlyzer' => 92458,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_DOROSTENCI.png',
        'csh'      => [
            ['slug' => '2-liga-mladsi-dorostenci-szc', 'sex' => 'muzi'],
        ],
    ],

    'dorost-starsi' => [
        'in_menu'  => false,   // sezóna 26/27: bez soutěže, hráči hrají 2. ligu mužů
        'menu_label' => 'DOROSTENCI starší',
        'title'    => 'Dorost starší',
        'label'    => 'LIONS DOROST STARŠÍ',
        'home_tag' => 'DOROSTENCI STARŠÍ',
        'photo'    => '2024/06/NK3_9206.png',
        'heading'  => 'DOROSTENCI STARŠÍ',
        'info'     => ['chlapci ročníku 2010 a 2011 (sezóna 26/27)', '**trenér:** RAMS Petr, ČEPÁK Radoslav, KRAUS Karel'],
        'training_title' => 'TRÉNINK 4x týdně:',
        'training' => [
            'PONDĚLÍ … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'ÚTERÝ … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'ČTVRTEK … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
            'PÁTEK … 18:30h – 20:00h … LIONS Aréna Hostivice – Břve',
        ],
        'notes'    => ['utkání 2. ligy házené mužů', 'členský příspěvek pololetí: 5.900,- Kč'],
        'cta'      => false,
        'register' => false,
        'sportlyzer' => 92459,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_DOROSTENCI.png',
        'csh'      => [],
    ],

    'zeny' => [
        'in_menu'  => true,
        'menu_label' => 'ŽENY',
        'title'    => 'Ženy',
        'label'    => 'LIONS ŽENY',
        'home_tag' => 'ŽENY',
        'photo'    => null,
        'heading'  => 'ŽENY',
        'info'     => [],
        'training_title' => 'TRÉNINK:',
        'training' => [],
        'notes'    => ['utkání 2. ligy házené žen – Čechy 2 o víkendu'],
        'cta'      => false,
        'register' => false,
        'sportlyzer' => 93168,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_ZENY.png',
        'partners' => [
            ['https://www.prevodyzdarma.cz/', '2024/08/PREVODYZDARMA.CZ-LogoSet-transparent-ver.4.2-300x100.png', 'PREVODYZDARMA.CZ'],
        ],
        'csh'      => [
            ['slug' => 'liga-zeny-cechyyy', 'sex' => 'zeny'],
        ],
    ],

    'muzi' => [
        'in_menu'  => true,
        'menu_label' => 'MUŽI',
        'title'    => 'Muži',
        'label'    => 'LIONS MUŽI',
        'home_tag' => 'MUŽI',
        'photo'    => '2024/06/NK3_9206.png',
        'heading'  => 'MUŽI',
        'info'     => [],
        'training_title' => 'TRÉNINK:',
        'training' => [],
        'notes'    => ['utkání 2. ligy házené mužů SZČ o víkendu'],
        'cta'      => false,
        'register' => false,
        'sportlyzer' => 92467,
        'jersey'   => '2024/08/LIONS-JERSEY-NEW-2023_ALL_DOROSTENCI.png',
        'csh'      => [
            ['slug' => '2-liga-muzi-szc', 'sex' => 'muzi'],
        ],
    ],
];
